---
# tasks file for mod-php7
- name: Assertions
  assert:
    that:
        - ansible_os_family == 'Debian'

- name: APT install
  apt:
      name: libapache2-mod-php7.0
      state: present
      update_cache: yes
      cache_valid_time: 3600

- name: Enable PHP module
  apache2_module:
      name: php7.0
      state: present
  notify:
      - Restart Apache
